name: Deploy mdBook to GitHub Pages

on:
  push:
    branches:
      - main  # Или master, в зависимости от названия вашей основной ветки

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Разрешаем менять содержимое (для пуша в ветку gh-pages)
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v6.0.0  # https://github.com/marketplace/actions/checkout

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1

      - name: install mdbook-admonish
        run: cargo install mdbook-admonish --vers "1.20.0" --locked

      - name: Setup mdbook-admonish
        run: mdbook-admonish install

      # Установка mdbook
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'
      # Сборка книги (создаст папку book/)
      - run: mdbook build

      # Публикация папки book/ в ветку gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4   # https://github.com/peaceiris/actions-gh-pages
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book