name: Deploy mdBook to GitHub Pages

on:
  push:
    branches:
      - main  # Или master, в зависимости от названия вашей основной ветки

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Разрешаем менять содержимое (для пуша в ветку gh-pages)
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v6.0.0  # https://github.com/marketplace/actions/checkout

      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | cargo-binstall
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Setup | Install | mdbook
        run: |
          cargo binstall -y mdbook

      - name: Build | Docs
        run: |
          mdbook build

      # Публикация папки book/ в ветку gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4   # https://github.com/peaceiris/actions-gh-pages
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book